### ISSUE TITLE
[API][discussion] Create a CRD for study

### ISSUE THREAD

**Issue by gaocegege** [kubeflow/katib#6] opened 2018-04-04 10:16 UTC
We have some discussions on slack and I have a idea to define a CRD and operator to manage studies, thus we could eliminate the customized CLI `katib-cli` and reuse `kubectl` to do the same thing.

I opened the issue to keep track of the idea.

**Comment by ddysher** [comment] 2018-04-16 06:53
Two random thoughts:

- should we create CRD for trails as well?
- since hyper-tuning system is fairly standalone system, we might also consider using API aggregation, which gives you higher flexibility, e.g. we can keep using mysql as our storage backend but provides the same API interface to katib users

**Comment by gaocegege** [comment] 2018-04-16 06:57
Yeah, I think so. API aggregation is more appropriate

**Comment by gaocegege** [comment] 2018-04-16 07:00
I am not sure if we should create CRD for trails, since we define it in study config. Thus I think we could treat it as worker/ps in TensorFlow.

**Comment by jlewi** [comment] 2018-07-07 01:54
Duplicate of #87

**Closed by jlewi** 2018-07-07 01:54 UTC
Labels: area/api, community/discussion, priority/p3
