### ISSUE TITLE
StudyName field is  unnecessary

### ISSUE THREAD

**Issue by hougangliu** [kubeflow/katib#380] opened 2019-02-15 00:50 UTC
When create a studyJob, we need specify its name in metadata.name. But we have studyName filed in studyJob.spec, too. I think .spec.StudyName is unnecessary. We can remove it.

```
type StudyJobSpec struct {
	StudyName            string                `json:"studyName,omitempty"`
       ...
}
```

**Comment by johnugeorge** [comment] 2019-02-15 02:41
@YujiOshima Was there some discussion about this before?

**Comment by YujiOshima** [comment] 2019-02-15 03:17
@johnugeorge @hougangliu We have discussed this here https://github.com/kubeflow/katib/pull/152#discussion_r212744338 .
In this PR https://github.com/kubeflow/katib/pull/352 I try to add `reusestudyid` field.
From this PR, we will use `StudyName` only when creating study and use `reusestudyid` in a studyjob for an existing study.
If we merge metadata.name and .spec.StudyName, I worry about a situation below.
We create a studyjob with `reusestudyid`. It will use an existing study.
Then the metadata.name of the studyjob and the name of study corresponding to the studyjob will be different. 
It may be confusing.

**Comment by hougangliu** [comment] 2019-02-15 04:12
@YujiOshima As you say, when we create a studyjob with `reusestudyid`. It will use an existing study. If we don't remove  spec.StudyName. the metadata.name of the studyjob and the name of study corresponding to the studyjob will be different (this is really confusing).

for now, I have no idea what we can use spec.StudyName for.

**Comment by johnugeorge** [comment] 2019-02-15 05:08
i agree with @hougangliu. as in the comment, do we really need to support "You can create multiple StudyJob for the same Study."

**Comment by YujiOshima** [comment] 2019-02-15 05:29
@johnugeorge I think it is needed. 

The use cases are
* To get initial values for bayesian opt, running random or manual studyjob. After that, run bayesian opt job reusing the StudyID.
* Want to retry or try another algorithm after a job is completed. And need to see all results on the same graph in UI
* Add a trail manually during job running since the algorithm doesn't search near the trial.

How about moving `.spec.StudyName` to `.status.StudyName`?
And it will be set by studyjob operator. When creating a study, it will be studyjobName. When reusing a study, it will be the name of the corresponding study.
Thought?

**Comment by johnugeorge** [comment] 2019-02-15 05:42
> i agree with @hougangliu. as in the comment, do we really need to support "You can create multiple StudyJob for the same Study."

I see.  I didn't realize that you meant reuseStudy by that comment.

**Comment by hougangliu** [comment] 2019-02-15 05:53
@YujiOshima 
I think moving `.spec.StudyName` to `.status.StudyName` is ok, which is filled by studyjob controller automatically.
I just wonder if we even drop .status.StudyName, is there any problem? or when we keep .status.StudyName, what this field we plan to use for?

**Comment by YujiOshima** [comment] 2019-02-15 06:08
@johnugeorge @hougangliu I expected that users can know which study the job working for easily by `.status.StudyName`.  But we can get it by `.status.StudyId` and it is enough.
We can drop `.status.StudyName`.

**Comment by richardsliu** [comment] 2019-03-27 20:44
Duplicate of #370 
/close

**Closed by richardsliu** 2019-03-27 20:44 UTC
