### ISSUE TITLE
the question about the requestNumber

### ISSUE THREAD

**Issue by wukong1992** [kubeflow/katib#161] opened 2018-08-31 02:03 UTC
I create a studyjobs, and it continue create pods, and I configure the requestNumber  "3", I didn't know the specfic implementation in the katib,

**Comment by wukong1992** [comment] 2018-08-31 12:59
I didn't exactly know the meaning of requestNmber，the number of workers at the same time?

**Comment by YujiOshima** [comment] 2018-09-04 04:14
@wukong1992 Yes.  The meaning of requestNmber is the maximum number of workers in parallel.

**Comment by richardsliu** [comment] 2019-01-25 01:55
@YujiOshima I think in future versions of the katib API we should make this clearer. For example, "requestCount" and "requestNumber" are both present in the schema, and it is not obvious what they mean.

**Comment by jlewi** [comment] 2019-03-10 22:53
Duplicate of #370

**Closed by jlewi** 2019-03-10 22:53 UTC
Labels: area/0.5.0, cuj/hp-tuning
