### ISSUE TITLE
How to use tensorflow-gpu?

### ISSUE THREAD

**Issue by warf34** [kubeflow/katib#705] opened 2019-07-31 07:24 UTC
I would like to use katib in Minikube with tensorflow-gpu.
I downloaded katib [here](https://github.com/kubeflow/katib) and run this [deploy.sh](https://github.com/kubeflow/katib/blob/master/examples/v1alpha2/MinikubeDemo/deploy.sh)
it works well In docker, but does not work in katib
how to use katib with tensorflow-gpu?
Do I need to install additional?

below are my files

Dockerfile
```
FROM python:3.7

RUN pip3 install tensorflow-gpu

ADD * ./
WORKDIR ./
```

mnist.py
```
import tensorflow as tf
import argparse
import time

from tensorflow.examples.tutorials.mnist import input_data

mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)

parser = argparse.ArgumentParser()
parser.add_argument("--lr",type=float,help="Input")
args = parser.parse_args()

start = time.time()
# parameters
learning_rate = args.lr
training_epochs = 10
batch_size = 100

# input place holders
X = tf.placeholder(tf.float32, [None, 784])
Y = tf.placeholder(tf.float32, [None, 10])

# weights & bias for nn layers
W1 = tf.get_variable("W1", shape=[784, 512],
                     initializer=tf.contrib.layers.xavier_initializer())
b1 = tf.Variable(tf.random_normal([512]))
L1 = tf.nn.relu(tf.matmul(X, W1) + b1)

W2 = tf.get_variable("W2", shape=[512, 512],
                     initializer=tf.contrib.layers.xavier_initializer())
b2 = tf.Variable(tf.random_normal([512]))
L2 = tf.nn.relu(tf.matmul(L1, W2) + b2)

W3 = tf.get_variable("W3", shape=[512, 512],
                     initializer=tf.contrib.layers.xavier_initializer())
b3 = tf.Variable(tf.random_normal([512]))
L3 = tf.nn.relu(tf.matmul(L2, W3) + b3)

W4 = tf.get_variable("W4", shape=[512, 512],
                     initializer=tf.contrib.layers.xavier_initializer())
b4 = tf.Variable(tf.random_normal([512]))
L4 = tf.nn.relu(tf.matmul(L3, W4) + b4)

W5 = tf.get_variable("W5", shape=[512, 10],
                     initializer=tf.contrib.layers.xavier_initializer())
b5 = tf.Variable(tf.random_normal([10]))
hypothesis = tf.matmul(L4, W5) + b5

# define cost/loss & optimizer
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(
    logits=hypothesis, labels=Y))
optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(cost)

# initialize
sess = tf.Session()
sess.run(tf.global_variables_initializer())

# train my model
for epoch in range(training_epochs):
    avg_cost = 0
    total_batch = int(mnist.train.num_examples / batch_size)

    for i in range(total_batch):
        batch_xs, batch_ys = mnist.train.next_batch(batch_size)
        feed_dict = {X: batch_xs, Y: batch_ys}
        c, _ = sess.run([cost, optimizer], feed_dict=feed_dict)
        avg_cost += c / total_batch

    print('Epoch:', '%04d' % (epoch + 1), 'cost =', '{:.9f}'.format(avg_cost))

print('Learning Finished!')

# Test model and check accuracy
correct_prediction = tf.equal(tf.argmax(hypothesis, 1), tf.argmax(Y, 1))
acc = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
accuracy = sess.run(acc, feed_dict={X: mnist.test.images, Y: mnist.test.labels})
print('accuracy=%f' % accuracy)
end = time.time()
result_time = end - start
print(result_time)
```

random.yaml
```
apiVersion: "kubeflow.org/v1alpha2"
kind: Experiment
metadata:
  namespace: kubeflow
  name: random-mnist-gpu
spec:
  parallelTrialCount: 3
  maxTrialCount: 12
  maxFailedTrialCount: 3
  objective:
    type: maximize
    goal: 0.99
    objectiveMetricName: "accuracy"
    additionalMetricNames:
  algorithm:
    algorithmName: random
  trialTemplate:
    goTemplate:
        rawTemplate: |-
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: {{.Trial}}
            namespace: {{.NameSpace}}
          spec:
            template:
              spec:
                containers:
                - name: {{.Trial}}
                  image: warf34/mnist-gpu:latest
                  command:
                  - "python3"
                  - "mnist.py"
                  {{- with .HyperParameters}}
                  {{- range .}}
                  - "{{.Name}}={{.Value}}"
                  {{- end}}
                  {{- end}}
                restartPolicy: Never
  parameters:
    - name: --lr
      parameterType: double
      feasibleSpace:
        min: "0.001"
        max: "0.003"
```

**Comment by gaocegege** [comment] 2019-07-31 07:32
You need to define resources in rawTemplate to require GPUs for the container.

**Comment by warf34** [comment] 2019-07-31 12:24
> You need to define resources in rawTemplate to require GPUs for the container.

I saw nasjob-example-RL.yaml and changed the container as shown below.
But it does not work. Is this wrong?
```
              spec:
                containers:
                - name: {{.Trial}}
                  image: warf34/mnist-gpu:latest
                  command:
                  - "python3"
                  - "mnist.py"
                  {{- with .HyperParameters}}
                  {{- range .}}
                  - "{{.Name}}={{.Value}}"
                  {{- end}}
                  {{- end}}
                  resources:
                    limits:
                      nvidia.com/gpu: 1
                restartPolicy: Never
```

**Comment by hougangliu** [comment] 2019-08-01 06:47
can you show us the related Pod by "kubectl describe"?

**Comment by warf34** [comment] 2019-08-01 09:18
> can you show us the related Pod by "kubectl describe"?

If i entered command "kubectl get po -n kubeflow", it show like below
```
NAME                                                    READY   STATUS    RESTARTS   AGE
katib-controller-7f985d6cd6-jwcfk                       1/1     Running   1          49m
katib-db-b48df7777-t7g5b                                1/1     Running   0          49m
katib-manager-7946dd5984-gvpqp                          1/1     Running   0          49m
katib-manager-rest-647f694b7d-vfp45                     1/1     Running   0          49m
katib-suggestion-bayesianoptimization-94c87dd64-lfhct   1/1     Running   0          49m
katib-suggestion-grid-58d9dfb5fd-wrlhc                  1/1     Running   0          48m
katib-suggestion-hyperband-778bb768c8-gmfgz             1/1     Running   0          48m
katib-suggestion-nasrl-d84fbb8f4-pdwmx                  1/1     Running   0          48m
katib-suggestion-random-7f96c4d77b-5jd68                1/1     Running   0          49m
katib-ui-6cf97db464-8zrkh                               1/1     Running   0          48m
random-mnist-gpu-psgqx427-z985z                         0/1     Pending   0          5m23s
random-mnist-gpu-rl6ds9d6-gn72t                         0/1     Pending   0          5m23s
random-mnist-gpu-v6w4rk67-78gqm                         0/1     Pending   0          5m23s
```

logs are below
```
{"level":"error","ts":1564650302.02284,"logger":"experiment-controller","caller":"experiment/experiment_controller.go:250","msg":"Create experiment in DB error","Experiment":"kubeflow/random-mnist-gpu","error":"rpc error: code = Unknown desc = Error 1062: Duplicate entry 'random-mnist-gpu' for key 'name'","stacktrace":"github.com/kubeflow/katib/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/kubeflow/katib/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/kubeflow/katib/pkg/controller/v1alpha2/experiment.(*ReconcileExperiment).Reconcile\n\t/go/src/github.com/kubeflow/katib/pkg/controller/v1alpha2/experiment/experiment_controller.go:250\ngithub.com/kubeflow/katib/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/kubeflow/katib/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:207\ngithub.com/kubeflow/katib/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/kubeflow/katib/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:157\ngithub.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
{"level":"error","ts":1564650302.0230024,"logger":"kubebuilder.controller","caller":"controller/controller.go:209","msg":"Reconciler error","Controller":"experiment-controller","Request":"kubeflow/random-mnist-gpu","error":"rpc error: code = Unknown desc = Error 1062: Duplicate entry 'random-mnist-gpu' for key 'name'","stacktrace":"github.com/kubeflow/katib/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/kubeflow/katib/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/kubeflow/katib/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/kubeflow/katib/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:209\ngithub.com/kubeflow/katib/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/kubeflow/katib/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:157\ngithub.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
{"level":"info","ts":1564650303.0239356,"logger":"experiment-controller","caller":"experiment/experiment_controller.go:347","msg":"CreateTrials","Experiment":"kubeflow/random-mnist-gpu","addCount":3}
{"level":"info","ts":1564650303.1141796,"logger":"experiment-status-util","caller":"util/status_util.go:72","msg":"Objective metric name not found","trial":"random-mnist-gpu-psgqx427"}
{"level":"info","ts":1564650303.1142302,"logger":"experiment-status-util","caller":"util/status_util.go:72","msg":"Objective metric name not found","trial":"random-mnist-gpu-rl6ds9d6"}
{"level":"info","ts":1564650303.1142774,"logger":"experiment-status-util","caller":"util/status_util.go:72","msg":"Objective metric name not found","trial":"random-mnist-gpu-v6w4rk67"}
...
{"level":"info","ts":1564650303.3270493,"logger":"trial-controller","caller":"trial/trial_controller.go:262","msg":"Creating Job","Trial":"kubeflow/random-mnist-gpu-psgqx427","kind":"Job","name":"random-mnist-gpu-psgqx427"}
{"level":"info","ts":1564650303.3643112,"logger":"trial-controller","caller":"trial/trial_controller.go:340","msg":"Creating Metrics Collector","Trial":"kubeflow/random-mnist-gpu-psgqx427","name":"random-mnist-gpu-psgqx427","namespace":"kubeflow"}
{"level":"info","ts":1564650303.4092865,"logger":"experiment-status-util","caller":"util/status_util.go:72","msg":"Objective metric name not found","trial":"random-mnist-gpu-psgqx427"}
{"level":"info","ts":1564650303.409339,"logger":"experiment-status-util","caller":"util/status_util.go:72","msg":"Objective metric name not found","trial":"random-mnist-gpu-rl6ds9d6"}
{"level":"info","ts":1564650303.4093537,"logger":"experiment-status-util","caller":"util/status_util.go:72","msg":"Objective metric name not found","trial":"random-mnist-gpu-v6w4rk67"}
```

**Comment by johnugeorge** [comment] 2019-08-01 10:43
Lets see one issue to track this. 

Can you check the events of pod to see why it is pending?
kubectl describe pod random-mnist-gpu-psgqx427-z985z

**Comment by warf34** [comment] 2019-08-01 11:17
> Lets see one issue to track this.
> 
> Can you check the events of pod to see why it is pending?
> kubectl describe pod random-mnist-gpu-psgqx427-z985z

An error message is displayed.
Error from server (NotFound): pods "random-mnist-gpu-psgqx427-z985z" not found

and if i entered "kubectl get trials -n kubeflow", all experiment is running
```
random-mnist-gpu-psgqx427   Running   129m
random-mnist-gpu-rl6ds9d6   Running   129m
random-mnist-gpu-v6w4rk67   Running   129m
```

**Comment by johnugeorge** [comment] 2019-08-01 12:51
you didn't provide namespace i guess.  
`kubectl describe pod random-mnist-gpu-psgqx427-z985z -n kubeflow`

**Comment by warf34** [comment] 2019-08-01 13:22
> you didn't provide namespace i guess.
> `kubectl describe pod random-mnist-gpu-psgqx427-z985z -n kubeflow`

It is printed as follows.
```
Name:           random-mnist-gpu-psgqx427-1564665540-pn66q
Namespace:      kubeflow
Priority:       0
Node:           minikube/10.0.2.15
Start Time:     Thu, 01 Aug 2019 22:19:08 +0900
Labels:         controller-uid=4284ae10-c455-42fd-9c8d-98ba837ba1a3
                job-name=random-mnist-gpu-psgqx427-1564665540
Annotations:    <none>
Status:         Pending
IP:             
Controlled By:  Job/random-mnist-gpu-psgqx427-1564665540
Containers:
  random-mnist-gpu-psgqx427:
    Container ID:  
    Image:         gcr.io/kubeflow-images-public/katib/v1alpha2/metrics-collector
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      ./metricscollector
    Args:
      -e
      random-mnist-gpu
      -t
      random-mnist-gpu-psgqx427
      -k
      Job
      -n
      kubeflow
      -m
      katib-manager.kubeflow:6789
      -mn
      accuracy
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from metrics-collector-token-xgjgj (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  metrics-collector-token-xgjgj:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  metrics-collector-token-xgjgj
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  2s    default-scheduler  Successfully assigned kubeflow/random-mnist-gpu-psgqx427-1564665540-pn66q to minikube
  Normal  Pulled     1s    kubelet, minikube  Container image "gcr.io/kubeflow-images-public/katib/v1alpha2/metrics-collector" already present on machine
  Normal  Created    1s    kubelet, minikube  Created container random-mnist-gpu-psgqx427
  Normal  Started    0s    kubelet, minikube  Started container random-mnist-gpu-psgqx427

Name:           random-mnist-gpu-psgqx427-z985z
Namespace:      kubeflow
Priority:       0
Node:           <none>
Labels:         controller-uid=59e4d8d6-0b26-4cc5-abbe-34bf4b49b030
                job-name=random-mnist-gpu-psgqx427
Annotations:    <none>
Status:         Pending
IP:             
Controlled By:  Job/random-mnist-gpu-psgqx427
Containers:
  random-mnist-gpu-psgqx427:
    Image:      warf34/mnist-gpu:latest
    Port:       <none>
    Host Port:  <none>
    Command:
      python3
      mnist.py
      --lr=0.0010284530740462016
    Limits:
      nvidia.com/gpu:  1
    Requests:
      nvidia.com/gpu:  1
    Environment:       <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-6vxwp (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  default-token-6vxwp:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-6vxwp
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                   From               Message
  ----     ------            ----                  ----               -------
  Warning  FailedScheduling  4m (x505 over 4h14m)  default-scheduler  0/1 nodes are available: 1 Insufficient nvidia.com/gpu.
```

**Comment by johnugeorge** [comment] 2019-08-01 13:34
Nodes are not detected with GPU. Hence, it is waiting  to get scheduled

**Comment by warf34** [comment] 2019-08-01 13:54
> Nodes are not detected with GPU. Hence, it is waiting to get scheduled

How to detect a node on my GPU?
i already installed cuda 10.0 and nvidia-docker2
my code works fine in nvidia-docker.
Is there anything to install or configure?

**Comment by johnugeorge** [comment] 2019-08-01 15:21
Please have a look at kubernetes doc https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/

**Comment by warf34** [comment] 2019-08-05 08:32
> Please have a look at kubernetes doc https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/

i installed NVIDIA driver-430 and nvidia-docker 2.0.
my default runtime in '/etc/docker/daemon.json' is nvidia
like this
```
{
    "default-runtime": "nvidia",
    "runtimes": {
        "nvidia": {
            "path": "/usr/bin/nvidia-container-runtime",
            "runtimeArgs": []
        }
    }
}
```
 and last, i entered `kubectl create -f https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/1.0.0-beta/nvidia-device-plugin.yml` after [deploy](https://github.com/kubeflow/katib/blob/master/examples/v1alpha2/MinikubeDemo/deploy.sh)

but STATUS is still pending and the Event is the same as above.

**Comment by gaocegege** [comment] 2019-08-05 08:34
@warf34 I suggest running a simple job to test if GPU is enabled in your cluster. katib is not the first option to test if it works.

**Comment by warf34** [comment] 2019-08-05 08:49
> @warf34 I suggest running a simple job to test if GPU is enabled in your cluster. katib is not the first option to test if it works.

oh, my miskate... I forgot to write down
i did change Dockerfile
```
ARG cuda_version=10.0
ARG cudnn_version=7
FROM nvidia/cuda:${cuda_version}-cudnn${cudnn_version}-devel

# Install system packages
RUN apt-get update && apt-get install -y software-properties-common && \
      add-apt-repository ppa:deadsnakes/ppa && \
      apt-get update && \
      apt-get install -y --no-install-recommends \
      bzip2 \
      g++ \
      git \
      graphviz \
      libgl1-mesa-glx \
      libhdf5-dev \
      openmpi-bin \
      python3.6 \
      python3-pip \
      python3-setuptools \
      python3-dev \
      wget && \
    rm -rf /var/lib/apt/lists/*


ADD . /app
WORKDIR /app

RUN pip3 install --upgrade pip
RUN pip3 install --no-cache-dir -r requirements.txt
ENV PYTHONPATH /app
```
and i try to run my code using docker like this
`docker run warf34/mnist-gpu:latest python3 mnist.py --lr=0.001`
`nvidia-docker run warf34/mnist-gpu:latest python3 mnist.py --lr=0.001`
and `docker run --runtime=nvidia warf34/mnist-gpu:latest python3 mnist.py --lr=0.001`
this three command's result is same because using nvidia-docker!

Are there other methods to test that you recommend?

**Comment by warf34** [comment] 2019-08-07 05:23
oh... i found why GPU is not running,
if i enter this plugin `kubectl create -f https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/1.0.0-beta/nvidia-device-plugin.yml`,
it applied minikube like this
```
NAMESPACE     NAME                                                    READY   STATUS      RESTARTS   AGE
kube-system   nvidia-device-plugin-daemonset-tflt5                    1/1     Running     0          21h
```
And when I check the GPU
`kubectl get nodes "-o=custom-columns=NAME:.metadata.name,GPU:.status.allocatable.nvidia\.com/gpu"`

result is
```
NAME       GPU
minikube   <none>
```

**Comment by warf34** [comment] 2019-08-08 08:10
> Please have a look at kubernetes doc https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/

if you don't mind, can you tell me how to solve [this problem](https://github.com/kubeflow/katib/issues/712#issue-476719680)?

**Comment by gaocegege** [comment] 2019-09-26 02:30
@warf34 

AWS or GCP will be easy.

**Comment by gaocegege** [comment] 2019-09-26 02:31
/close

I am closing the issue since it is not a problem caused by katib. But feel free to add new comments if you still have problems on it.

**Closed by gaocegege** 2019-09-26 02:31 UTC
