### ISSUE TITLE
Metric collector containers are not added when deployed in non kubeflow namespace

### ISSUE THREAD

**Issue by johnugeorge** [kubeflow/katib#823] opened 2019-09-26 18:24 UTC
/kind bug

/assign @hougangliu

**Comment by hougangliu** [comment] 2019-09-27 01:51
For now, metrics-collector sidecar container is only injected into the namespace with label `katib-metricscollector-injection: enabled` by design

**Comment by gaocegege** [comment] 2019-09-27 01:52
Yeah, I think it is a feature to avoid performance issues.

**Comment by gaocegege** [comment] 2019-09-27 03:47
We decided to add a validation webhook to avoid silent failure.

**Comment by gaocegege** [comment] 2019-09-28 00:22
I think we could close it. https://github.com/kubeflow/katib/pull/828 fixed it.

/close

**Closed by gaocegege** 2019-09-28 00:22 UTC
Labels: kind/bug
